### ISSUE TITLE
template_render_figure_items.php - ORDER BY RAND() LIMIT 5  Error

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_3#45]
i get again this error:

i change it to ORDER BY RAND() LIMIT 0,5 but nothing

file will be found here: [https://github.com/Catzenjaeger/FigureLib_3/blob/master/infusions/figurelib/templates/template_render_figure_items%2Cphp](url)

`Driver/PDOMySQL.php
/test/infusions/figurelib/figures.php?figure_id=3
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY RAND() LIMIT 0,5' at line 15
Line: 108`

**Comment by DavidGuetl** [comment]
I have sent a private Message to you on the NSS, i fixed this Problem too ;)

**Comment by Catzenjaeger** [comment]
:) thank you so much i will check it and update the files here

**Comment by Catzenjaeger** [comment]
error unfortunately still exist

Driver/PDOMySQL.php
/test/infusions/figurelib/figures.php?figure_id=4
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY RAND() LIMIT 5' at line 15
Line: 108

**Comment by DavidGuetl** [comment]
Search in templates/template_render_figure_items.php at Line 776 for:

```
$result3 = dbquery("
						SELECT 
							f.figure_id, 
							f.figure_title, 
							f.figure_datestamp, 
							f.figure_visibility, 
							fc.figure_cat_id, 
							fc.figure_cat_name,
							fm.figure_manufacturer_id,
							fm.figure_manufacturer_name							
						FROM ".DB_FIGURE_ITEMS." f 
						INNER JOIN ".DB_FIGURE_CATS." fc ON f.figure_cat=fc.figure_cat_id
						INNER JOIN ".DB_FIGURE_MANUFACTURERS." fm ON f.figure_manufacturer=fm.figure_manufacturer_id 						
						WHERE MATCH (figure_title) AGAINST ('".$data['figure_title']."' IN BOOLEAN MODE) 
						AND figure_id != ".$data['figure_id']." ".(iSUPERADMIN ? "" : "AND ".groupaccess('figure_visibility'))." 
						ORDER BY RAND() LIMIT 5");
```

Replace it with
```
$result3 = dbquery("
						SELECT 
							f.figure_id, 
							f.figure_title, 
							f.figure_datestamp, 
							f.figure_visibility, 
							fc.figure_cat_id, 
							fc.figure_cat_name,
							fm.figure_manufacturer_id,
							fm.figure_manufacturer_name							
						FROM ".DB_FIGURE_ITEMS." f 
						INNER JOIN ".DB_FIGURE_CATS." fc ON f.figure_cat=fc.figure_cat_id
						INNER JOIN ".DB_FIGURE_MANUFACTURERS." fm ON f.figure_manufacturer=fm.figure_manufacturer_id 						
						WHERE MATCH (figure_title) AGAINST ('".$data['figure_title']."' IN BOOLEAN MODE) 
						AND figure_id != '".$data['figure_id']."' ".(iSUPERADMIN ? "" : "AND ".groupaccess('figure_visibility'))." 
						ORDER BY RAND() LIMIT 0,5");
```

**Comment by Catzenjaeger** [comment]
its not the solution ... i have try this before 100 times.  :(

**Comment by DavidGuetl** [comment]
Lol? It works at my Space fine ..

**Comment by Catzenjaeger** [comment]
ok i try it again :) thanx

**Comment by DavidGuetl** [comment]
Work it now?

**Comment by Catzenjaeger** [comment]
thanx --- at the moment no notice ... i will watch a while :)

**Comment by Catzenjaeger** [comment]
looks good i clode for the moment
